### ISSUE TITLE
streamlining the nomination and exile system

### ISSUE THREAD

**Issue by blurbthe** [pontaoski/mappo#33]
instead of nominating whoever and then individually exiling them, i think it would be better to just nominate as many people as you want, then whoever gets the most nominations is exiled. this simplifies the process into one step and just feels more intuitive. also i think in the case of a tie, neither should be exiled so that creates some interesting opportunities for evil roles.

also: don't announce votes. keep votes anonymous and only announce the totals at the end. in the case of the innocent role, announce the death of a good role (but don't explicitly state it's because of nominating the innocent), but don't say anything if it's from an evil role, and count it towards the totals at the end.

**Comment by pontaoski** [comment]
nomination system was streamlined
